version: "3.7"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
    - 80:80
    volumes:
    - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    - ./public/s:/usr/share/nginx/html/s:ro
    - ./public/index.html:/usr/share/nginx/html/index.html:ro
    - ./example:/usr/share/nginx/html/app:ro